apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers: 
      - name: book-catalog
        image: chapter8.azurecr.io/book-catalog:latest
        ports:
        - containerPort: 8000
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_URL
          value: "postgresql://proj3_gsqi_user:h8AxE2eeGbf3GtM4jk397UkcWZ9wNZ4I@dpg-crmmd09u0jms7396fff0-a.oregon-postgres.render.com/proj3_gsqi"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers: 
      - name: inventory-management
        image: chapter8.azurecr.io/inventory-management:latest
        ports:
        - containerPort: 8001
        imagePullPolicy: IfNotPresent
        env:
        - name: DATABASE_URL
          value: "postgresql://proj3_gsqi_user:h8AxE2eeGbf3GtM4jk397UkcWZ9wNZ4I@dpg-crmmd09u0jms7396fff0-a.oregon-postgres.render.com/proj3_gsqi"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management
spec:
  selector:
    app: inventory-management
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30001